import {
  CASE_STATUS,
  createCase,
  createPrescription,
  createSample,
  SAMPLE_STATUS,
} from '../domain';

export const mockStore = {
  users: [
    { id: 'USR-001', role: 'FARMER', name: 'Bhupesh Paliwal', mobile: '9876543210', status: 'ACTIVE' },
    { id: 'USR-002', role: 'SEVA_SAKHI', name: 'Janvi Madam', mobile: '9876543211', status: 'ACTIVE' },
    { id: 'USR-003', role: 'VETERINARIAN', name: 'Dr. Parth Gawde', mobile: '9876543212', status: 'ACTIVE' },
    { id: 'USR-004', role: 'KENDRA', name: 'Kavita Sharma', mobile: '9876543213', status: 'ACTIVE' },
  ],
  farmers: [{ farmerId: 'FR-4821', userId: 'USR-001', name: 'Bhupesh Paliwal', mobile: '9876543210', villageId: 'VIL-UDAIPUR', address: 'Udaipur, Rajasthan', preferredLanguage: 'hi' }],
  animals: [
    { rapidId: 'BLX-204', farmerId: 'FR-4821', species: 'CATTLE', breed: 'Tharparkar', sex: 'FEMALE', age: '4 years', healthStatus: 'HEALTHY', vaccinationStatus: 'CURRENT', status: 'ACTIVE' },
    { rapidId: 'BLX-118', farmerId: 'FR-4821', species: 'BUFFALO', breed: 'Murrah', sex: 'FEMALE', age: '6 years', healthStatus: 'MONITORING', vaccinationStatus: 'DUE', status: 'ACTIVE' },
  ],
  flocks: [{ flockId: 'FLK-017', farmerId: 'FR-4821', species: 'POULTRY', breed: 'Broiler', count: 240, age: '5 weeks', healthStatus: 'HEALTHY', vaccinationStatus: 'CURRENT', status: 'ACTIVE' }],
  cases: [createCase({ caseId: 'CASE-204', farmerId: 'FR-4821', animalId: 'BLX-204', submittedBy: 'USR-001', submittedAt: '2026-08-15T09:15:00.000Z', symptoms: ['reduced milk yield'], status: CASE_STATUS.VET_REVIEW, riskLevel: 'YELLOW', veterinarianId: 'USR-003' })],
  veterinarians: [{ id: 'USR-003', veterinarianId: 'USR-003', name: 'Dr. Parth Gawde', status: 'AVAILABLE', villages: ['VIL-UDAIPUR'] }],
  prescriptions: [],
  samples: [createSample({ sampleId: 'SAMPLE-1042', caseId: 'CASE-204', sampleType: 'MILK_CULTURE', kendraId: 'KEN-UDAIPUR', status: SAMPLE_STATUS.RECEIVED_AT_KENDRA, qrCodeReference: 'QR-SAMPLE-1042' })],
  medicines: [{ medicineId: 'MED-001', name: 'Veterinary supportive care', batch: 'B-2026-04', expiry: '2027-04-30', quantity: 120 }],
  inventory: [{ inventoryId: 'INV-001', kendraId: 'KEN-UDAIPUR', medicineId: 'MED-001', availableQuantity: 120, reservedQuantity: 0, usedQuantity: 0 }],
  inventoryTransactions: [],
  prescriptionOtps: [],
  alerts: [],
  riskZones: [
    {
      id: 'RZ-01',
      alertId: 'ALT-101',
      disease: 'Foot and Mouth Disease (FMD)',
      village: 'Udaipur Cluster',
      latitude: 24.5854,
      longitude: 73.7125,
      riskLevel: 'HIGH',
      casesCount: 8,
      radiusKm: 5,
      updatedAt: '2 hours ago',
      advisory: 'Isolate symptomatic livestock, enforce ring vaccination, avoid shared water points.',
    },
    {
      id: 'RZ-02',
      alertId: 'ALT-102',
      disease: 'Mastitis Surveillance Zone',
      village: 'Bharampur Region',
      latitude: 24.6200,
      longitude: 73.7500,
      riskLevel: 'MEDIUM',
      casesCount: 3,
      radiusKm: 3,
      updatedAt: '6 hours ago',
      advisory: 'Maintain strict teat dipping and hygiene during milking.',
    },
    {
      id: 'RZ-03',
      alertId: 'ALT-103',
      disease: 'Avian Influenza Monitoring',
      village: 'Nawada Sector',
      latitude: 24.5500,
      longitude: 73.6800,
      riskLevel: 'HIGH',
      casesCount: 12,
      radiusKm: 8,
      updatedAt: '1 hour ago',
      advisory: 'Restrict poultry movement, report sudden flock mortality immediately.',
    },
    {
      id: 'RZ-04',
      alertId: 'ALT-104',
      disease: 'Blackquarter (BQ) Watch',
      village: 'Kalka Mata Area',
      latitude: 24.6000,
      longitude: 73.6900,
      riskLevel: 'LOW',
      casesCount: 1,
      radiusKm: 4,
      updatedAt: '12 hours ago',
      advisory: 'Ensure annual BQ vaccination before monsoon.',
    },
  ],
  notifications: [],
  veterinarianAssessments: [],
  emergencyTasks: [],
  auditEvents: [],
};

export const appendAuditEvent = (event) => {
  const auditEvent = { id: `AUDIT-${Date.now()}`, createdAt: new Date().toISOString(), ...event };
  mockStore.auditEvents.push(auditEvent);
  return auditEvent;
};
