import {
  CASE_STATUS,
  createCase,
  createPrescription,
  createSample,
  SAMPLE_STATUS,
} from '../domain';

export const mockStore = {
  users: [
    { id: 'USR-001', role: 'FARMER', name: 'Bhupesh Paliwal', mobile: '9876543210', status: 'ACTIVE' },
    { id: 'USR-002', role: 'SEVA_SAKHI', name: 'Janvi Madam', mobile: '9876543211', status: 'ACTIVE' },
    { id: 'USR-003', role: 'VETERINARIAN', name: 'Dr. Parth Gawde', mobile: '9876543212', status: 'ACTIVE' },
    { id: 'USR-004', role: 'KENDRA', name: 'Kavita Sharma', mobile: '9876543213', status: 'ACTIVE' },
  ],
  farmers: [
    { farmerId: 'FR-4821', userId: 'USR-001', name: 'Bhupesh Paliwal', mobile: '9876543210', villageId: 'VIL-UDAIPUR', address: 'Udaipur Village', preferredLanguage: 'hi' },
    { farmerId: 'FR-4822', userId: 'USR-005', name: 'Sita Devi', mobile: '9876543214', villageId: 'VIL-BHARAMPUR', address: 'Bharampur Village', preferredLanguage: 'mr' },
    { farmerId: 'FR-4823', userId: 'USR-006', name: 'Ram Lal', mobile: '9876543215', villageId: 'VIL-NAWADA', address: 'Nawada Village', preferredLanguage: 'hi' },
    { farmerId: 'FR-4824', userId: 'USR-007', name: 'Anita Yadav', mobile: '9876543216', villageId: 'VIL-KALKAMATA', address: 'Kalka Mata Village', preferredLanguage: 'hi' },
    { farmerId: 'FR-4825', userId: 'USR-008', name: 'Ramesh Patel', mobile: '9876543217', villageId: 'VIL-RAMPUR', address: 'Rampur Village', preferredLanguage: 'mr' },
  ],
  villages: [
    { villageId: 'VIL-UDAIPUR', name: 'Udaipur Village', code: 'UDP-01', liveCasesCount: 8, highPriorityCount: 2, pendingSamplesCount: 1, kendraId: 'KEN-UDAIPUR', kendraName: 'Udaipur Pashu Seva Kendra', latitude: 24.5854, longitude: 73.7125 },
    { villageId: 'VIL-BHARAMPUR', name: 'Bharampur Village', code: 'BHP-02', liveCasesCount: 5, highPriorityCount: 1, pendingSamplesCount: 0, kendraId: 'KEN-BHARAMPUR', kendraName: 'Bharampur Seva Kendra', latitude: 24.6200, longitude: 73.7500 },
    { villageId: 'VIL-NAWADA', name: 'Nawada Village', code: 'NWD-03', liveCasesCount: 4, highPriorityCount: 2, pendingSamplesCount: 2, kendraId: 'KEN-NAWADA', kendraName: 'Nawada Pashu Kendra', latitude: 24.5500, longitude: 73.6800 },
    { villageId: 'VIL-KALKAMATA', name: 'Kalka Mata Village', code: 'KLK-04', liveCasesCount: 2, highPriorityCount: 0, pendingSamplesCount: 0, kendraId: 'KEN-KALKA', kendraName: 'Kalka Mata Seva Kendra', latitude: 24.6000, longitude: 73.6900 },
    { villageId: 'VIL-RAMPUR', name: 'Rampur Village', code: 'RMP-05', liveCasesCount: 3, highPriorityCount: 1, pendingSamplesCount: 1, kendraId: 'KEN-RAMPUR', kendraName: 'Rampur Animal Care Kendra', latitude: 24.5700, longitude: 73.7300 },
    { villageId: 'VIL-SUKHER', name: 'Sukher Village', code: 'SKH-06', liveCasesCount: 1, highPriorityCount: 0, pendingSamplesCount: 0, kendraId: 'KEN-SUKHER', kendraName: 'Sukher Seva Kendra', latitude: 24.6400, longitude: 73.7100 },
  ],
  sevaSakhis: [
    { sakhiId: 'SAKHI-101', userId: 'USR-002', name: 'Priya Jadhav', distanceKm: 2.1, status: 'AVAILABLE', mobile: '9876543211', villageId: 'VIL-UDAIPUR' },
    { sakhiId: 'SAKHI-102', userId: 'USR-009', name: 'Sunita Sharma', distanceKm: 3.4, status: 'AVAILABLE', mobile: '9876543220', villageId: 'VIL-BHARAMPUR' },
    { sakhiId: 'SAKHI-103', userId: 'USR-010', name: 'Anita Verma', distanceKm: 4.8, status: 'ON_FIELD', mobile: '9876543221', villageId: 'VIL-NAWADA' },
  ],
  animals: [
    { rapidId: 'BLX-204', farmerId: 'FR-4821', species: 'CATTLE', breed: 'Tharparkar', sex: 'FEMALE', age: '4 years', healthStatus: 'HEALTHY', vaccinationStatus: 'CURRENT', status: 'ACTIVE' },
    { rapidId: 'BLX-118', farmerId: 'FR-4821', species: 'BUFFALO', breed: 'Murrah', sex: 'FEMALE', age: '6 years', healthStatus: 'MONITORING', vaccinationStatus: 'DUE', status: 'ACTIVE' },
    { rapidId: 'BLX-347', farmerId: 'FR-4822', species: 'BUFFALO', breed: 'Jaffrabadi', sex: 'FEMALE', age: '5 years', healthStatus: 'SICK', vaccinationStatus: 'OVERDUE', status: 'ACTIVE' },
    { rapidId: 'BLX-521', farmerId: 'FR-4823', species: 'CATTLE', breed: 'Gir', sex: 'FEMALE', age: '3 years', healthStatus: 'MONITORING', vaccinationStatus: 'CURRENT', status: 'ACTIVE' },
  ],
  flocks: [
    { flockId: 'FLK-017', farmerId: 'FR-4821', species: 'POULTRY', breed: 'Broiler', count: 240, age: '5 weeks', healthStatus: 'HEALTHY', vaccinationStatus: 'CURRENT', status: 'ACTIVE' },
    { flockId: 'FLK-022', farmerId: 'FR-4825', species: 'POULTRY', breed: 'Layer', count: 150, age: '12 weeks', healthStatus: 'MONITORING', vaccinationStatus: 'CURRENT', status: 'ACTIVE' },
  ],
  cases: [
    createCase({
      caseId: 'CASE-204',
      farmerId: 'FR-4821',
      animalId: 'BLX-204',
      submittedBy: 'USR-001',
      submittedAt: '2026-08-15T09:15:00.000Z',
      symptoms: ['reduced milk yield', 'udder swelling'],
      originalSymptoms: 'गाईच्या आचळाला सूज आहे आणि दूध कमी झाले आहे.',
      originalLanguage: 'mr',
      status: CASE_STATUS.VET_REVIEW,
      riskLevel: 'YELLOW',
      aiPriority: 'HIGH',
      aiConfidence: 0.92,
      veterinarianId: 'USR-003',
      location: { village: 'Udaipur Village', latitude: 24.5854, longitude: 73.7125 },
      geotagMetadata: { latitude: 24.5854, longitude: 73.7125, locationAccuracy: '3.2m GPS lock' },
      photo: 'https://images.unsplash.com/photo-1570042707222-6b3a0937a003?auto=format&fit=crop&w=600&q=80',
      voiceNote: null,
      transcriptText: 'गाय २ दिवसांपासून वैरण खात नाही आणि दूध खूप कमी दिले आहे.'
    }),
    createCase({
      caseId: 'CASE-205',
      farmerId: 'FR-4822',
      animalId: 'BLX-347',
      submittedBy: 'USR-005',
      submittedAt: '2026-08-15T11:30:00.000Z',
      symptoms: ['high fever', 'mouth lesions', 'excess salivation'],
      originalSymptoms: 'म्हशीला तीव्र ताप आहे आणि तोंडातून लाळ गळत आहे.',
      originalLanguage: 'mr',
      status: CASE_STATUS.VET_REVIEW,
      riskLevel: 'RED',
      aiPriority: 'HIGH',
      aiConfidence: 0.96,
      veterinarianId: 'USR-003',
      location: { village: 'Bharampur Village', latitude: 24.6200, longitude: 73.7500 },
      geotagMetadata: { latitude: 24.6200, longitude: 73.7500, locationAccuracy: '2.5m GPS lock' },
    }),
    createCase({
      caseId: 'CASE-206',
      farmerId: 'FR-4823',
      animalId: 'BLX-521',
      submittedBy: 'USR-006',
      submittedAt: '2026-08-14T14:20:00.000Z',
      symptoms: ['coughing', 'nasal discharge'],
      originalSymptoms: 'गाय को बुखार और खांसी है।',
      originalLanguage: 'hi',
      status: CASE_STATUS.VET_REVIEW,
      riskLevel: 'YELLOW',
      aiPriority: 'MEDIUM',
      aiConfidence: 0.84,
      veterinarianId: 'USR-003',
      location: { village: 'Nawada Village', latitude: 24.5500, longitude: 73.6800 },
      geotagMetadata: { latitude: 24.5500, longitude: 73.6800, locationAccuracy: '4.1m GPS lock' },
    }),
    createCase({
      caseId: 'CASE-207',
      farmerId: 'FR-4824',
      animalId: 'BLX-118',
      submittedBy: 'USR-007',
      submittedAt: '2026-08-13T16:00:00.000Z',
      symptoms: ['minor hoof lesion'],
      originalSymptoms: 'खुर में हल्की चोट है।',
      originalLanguage: 'hi',
      status: CASE_STATUS.ACTION_REQUIRED,
      riskLevel: 'LOW',
      aiPriority: 'LOW',
      aiConfidence: 0.78,
      veterinarianId: 'USR-003',
      location: { village: 'Kalka Mata Village', latitude: 24.6000, longitude: 73.6900 },
    }),
    createCase({
      caseId: 'CASE-208',
      farmerId: 'FR-4825',
      flockId: 'FLK-022',
      submittedBy: 'USR-008',
      submittedAt: '2026-08-15T08:00:00.000Z',
      symptoms: ['poultry lethargy', 'respiratory rattle'],
      originalSymptoms: 'कोंबड्यांमध्ये मरतुक वाढली आहे आणि श्वास घ्यायला त्रास होतोय.',
      originalLanguage: 'mr',
      status: CASE_STATUS.VET_REVIEW,
      riskLevel: 'YELLOW',
      aiPriority: 'HIGH',
      aiConfidence: 0.91,
      veterinarianId: 'USR-003',
      location: { village: 'Rampur Village', latitude: 24.5700, longitude: 73.7300 },
    }),
  ],
  veterinarians: [{ id: 'USR-003', veterinarianId: 'USR-003', name: 'Dr. Parth Gawde', status: 'AVAILABLE', villages: ['VIL-UDAIPUR', 'VIL-BHARAMPUR', 'VIL-NAWADA', 'VIL-KALKAMATA', 'VIL-RAMPUR', 'VIL-SUKHER'] }],
  prescriptions: [],
  samples: [
    createSample({ sampleId: 'SAMPLE-1042', caseId: 'CASE-204', sampleType: 'MILK_CULTURE', kendraId: 'KEN-UDAIPUR', status: SAMPLE_STATUS.RECEIVED_AT_KENDRA, qrCodeReference: 'QR-SAMPLE-1042', assignedSakhiId: 'SAKHI-101' }),
    createSample({ sampleId: 'SAMPLE-1043', caseId: 'CASE-205', sampleType: 'BLOOD', kendraId: 'KEN-BHARAMPUR', status: SAMPLE_STATUS.REQUESTED, qrCodeReference: 'QR-SAMPLE-1043', assignedSakhiId: 'SAKHI-102' }),
    createSample({ sampleId: 'SAMPLE-1044', caseId: 'CASE-208', sampleType: 'SWAB', kendraId: 'KEN-RAMPUR', status: SAMPLE_STATUS.RESULT_AVAILABLE, qrCodeReference: 'QR-SAMPLE-1044', result: 'Viral Antigen Positive (Suspected Newcastle)', assignedSakhiId: 'SAKHI-103' }),
  ],
  medicines: [
    { medicineId: 'MED-001', name: 'Veterinary supportive care (Anti-inflammatory)', batch: 'B-2026-04', expiry: '2027-04-30', quantity: 120, unit: 'Bottles' },
    { medicineId: 'MED-002', name: 'Broad Spectrum Antibiotic Injection', batch: 'B-2026-08', expiry: '2027-08-15', quantity: 18, unit: 'Vials' },
    { medicineId: 'MED-003', name: 'Teat Dip Disinfectant & Udder Gel', batch: 'B-2026-01', expiry: '2026-12-31', quantity: 0, unit: 'Packs' },
    { medicineId: 'MED-004', name: 'FMD Ring Vaccine Dose', batch: 'VAC-2026-09', expiry: '2027-09-30', quantity: 250, unit: 'Doses' },
  ],
  inventory: [
    { inventoryId: 'INV-001', kendraId: 'KEN-UDAIPUR', medicineId: 'MED-001', availableQuantity: 120, reservedQuantity: 0, usedQuantity: 0, status: 'AVAILABLE' },
    { inventoryId: 'INV-002', kendraId: 'KEN-UDAIPUR', medicineId: 'MED-002', availableQuantity: 18, reservedQuantity: 0, usedQuantity: 5, status: 'LOW_STOCK' },
    { inventoryId: 'INV-003', kendraId: 'KEN-UDAIPUR', medicineId: 'MED-003', availableQuantity: 0, reservedQuantity: 0, usedQuantity: 40, status: 'OUT_OF_STOCK' },
    { inventoryId: 'INV-004', kendraId: 'KEN-UDAIPUR', medicineId: 'MED-004', availableQuantity: 250, reservedQuantity: 0, usedQuantity: 50, status: 'AVAILABLE' },
  ],
  stockRefillRequests: [],
  inventoryTransactions: [],
  prescriptionOtps: [],
  alerts: [],
  riskZones: [
    {
      id: 'RZ-01',
      alertId: 'ALT-101',
      disease: 'Foot and Mouth Disease (FMD)',
      village: 'Udaipur Village',
      latitude: 24.5854,
      longitude: 73.7125,
      riskLevel: 'HIGH',
      casesCount: 8,
      radiusKm: 5,
      updatedAt: '2 hours ago',
      advisory: 'Isolate symptomatic livestock, enforce ring vaccination, avoid shared water points.',
    },
    {
      id: 'RZ-02',
      alertId: 'ALT-102',
      disease: 'Mastitis Surveillance Zone',
      village: 'Bharampur Village',
      latitude: 24.6200,
      longitude: 73.7500,
      riskLevel: 'MEDIUM',
      casesCount: 3,
      radiusKm: 3,
      updatedAt: '6 hours ago',
      advisory: 'Maintain strict teat dipping and hygiene during milking.',
    },
    {
      id: 'RZ-03',
      alertId: 'ALT-103',
      disease: 'Avian Influenza Monitoring',
      village: 'Nawada Village',
      latitude: 24.5500,
      longitude: 73.6800,
      riskLevel: 'HIGH',
      casesCount: 12,
      radiusKm: 8,
      updatedAt: '1 hour ago',
      advisory: 'Restrict poultry movement, report sudden flock mortality immediately.',
    },
    {
      id: 'RZ-04',
      alertId: 'ALT-104',
      disease: 'Blackquarter (BQ) Watch',
      village: 'Kalka Mata Village',
      latitude: 24.6000,
      longitude: 73.6900,
      riskLevel: 'LOW',
      casesCount: 1,
      radiusKm: 4,
      updatedAt: '12 hours ago',
      advisory: 'Ensure annual BQ vaccination before monsoon.',
    },
  ],
  notifications: [],
  veterinarianAssessments: [],
  emergencyTasks: [],
  auditEvents: [],
};

export const appendAuditEvent = (event) => {
  const auditEvent = { id: `AUDIT-${Date.now()}`, createdAt: new Date().toISOString(), ...event };
  mockStore.auditEvents.push(auditEvent);
  return auditEvent;
};
